server:
  port: 8082

spring:
  application:
    name: ORDERS-SERVICE
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 1
        ignoreExceptions: feign.FeignException.NotFound
    instances:
      user-api:
        waitDurationInOpenState: 10s
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        ignoreExceptions: feign.FeignException.NotFound
    instances:
      user-api:
        baseConfig: default

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers, prometheus